## Que retenir de tout ça ?
- Il y a des opportunités pour l'INSEE et ses agents dans toutes les sphères !
- usages possibles : 
    - automatisation des tâches redondantes
    - production facilitée de documentation
    - chats spécialisés dans un domaine (RAG) 
    - aide précieuse en programmation (cursor démonstration + documentation via github)
- glissements des agents converationnels vers les agents réalisant des actions ! (bolt.new)

# La contrepartie 
- [**Formations**]{.orange} nécessaires sur l'usage de ces outils
- redéfinition possible de certains [**rôles**]{.blue2} :
    - l'exemple de [**sirene**]{.orange} : + classification automatique des [**APE**]{.blue2}
    - données [**satellites**]{.orange} + enquete cartographique
- Nécessite une [**mise à jour**]{.blue2} assez fréquente 

## Attention aux données !:

- Avec de [**mauvaises données**]{.blue2} on aura toujours de [**mauvais résultats**]{.orange} !
- mauvaises images → mauvaises prédictions
- mauvais corpus de texte → mauvais agents conversationnels

## Attention à l'organisation :
- L'[**automatisation**]{.orange} demande de la rigueur ! :
    - [**stabilité**]{.blue2} dans les formats de données
    - Mise à jour intelligente des sources de données
    - [**parcimonie**]{.orange} dans les programmes
    - [**Documentation**]{.orange} des programmes
- nécessite une vraie [**culture de la donnée**]{.orange} !
- notions de bonnes pratiques : Git/Gitlab, integration continue

## L'écosystème INSEE

- Ces outils sont-ils disponibles à l'INSEE ?
- Listes des ressources :
    - datalab
    - AUS 
    - LS3
    
